(ns peher.services.raga)

(def raga-list
 {:first   ["Raga Malkauns"
            "Raga Bageshree"
            "Raga Bahar"
            "Raga Basant Bahar"
            "Raga Des"
            "Raga Kaushi Kanada"
            "Raga Manjh Khamaj"
            "Raga Adana"
            "Raga Basant Pancham"
            "Raga Kanak Basant"
            "Raga Bhavani"
            "Raga Chandrika"
            "Raga Daulati"
            "Raga Homshikha"
            "Raga Jairaj"
            "Raga Jog"
            "Raga Jogkauns"
            "Raga Jungala"
            "Raga Kafi Kanada"
            "Raga Sangam Kedar"
            "Raga Lajwanti"
            "Raga Madhuri"
            "Raga Pancham Malkauns"
            "Raga Sampoorna Malkauns"
            "Raga Manjiri"
            "Raga Nupur"
            "Raga Paraj"
            "Raga Pushp Ranjani"
            "Raga Ras Ranjani"
            "Raga Shree Ranjani"
            "Raga Yash Ranjani"]

  :second  ["Raga Basant"
            "Raga Sohoni"
            "Raga Hindol"
            "Raga Lalit"
            "Raga Bhatiyar"
            "Raga Paraj Bahar"
            "Raga Dhanya Dhaivat"
            "Raga Hevitri"
            "Raga Bhankar"
            "Raga Hindol Bahar"
            "Raga Marg Hindol"
            "Raga Sampoorna Hindol"
            "Raga Jayant"
            "Raga Kalingda"
            "Raga Lalitkali"
            "Raga Mevada"
            "Raga Megh Ranjani"]

  :third   ["Raga Bhairav"
            "Raga Ahir Bhairav"
            "Raga Ahiri"
            "Raga Anand Leela"
            "Raga Araj"
            "Raga Bhairav Bahar"
            "Raga Basant Mukhari"
            "Raga Gambhir Basant"
            "Raga Anand Bhairav"
            "Raga Bairagi Bhairav"
            "Raga Bangal Bhairav"
            "Raga Hijaj Bhairav"
            "Raga Kabir Bhairav"
            "Raga Kaushi Bhairav"
            "Raga Komal Bhairav"
            "Raga Mangal Bhairav"
            "Raga Nat Bhairav"
            "Raga Prabhaat Bhairav"
            "Raga Saveri Bhairav"
            "Raga Shivmat Bhairav"
            "Raga Sourashtra Bhairav"
            "Raga Udasi Bhairav"
            "Raga Bhairavi"
            "Raga Bibhas"
            "Raga Bilawal"
            "Raga Alahaiya Bilawal"
            "Raga Devgiri Bilawal"
            "Raga Kukubh Bilawal"
            "Raga Sarpada Bilawal"
            "Raga Shukla Bilawal"
            "Raga Yamani Bilawal"
            "Raga Desh Gaud"
            "Raga Deskar"
            "Raga Gandhakriya"
            "Raga Gara"
            "Raga Girija"
            "Raga Gopika Basant"
            "Raga Gunakali"
            "Raga Utari Gunakali"
            "Raga Hemavanti"
            "Raga Jogiya"
            "Raga Kakambheri"
            "Raga Shree Kalyan"
            "Raga Kolahal"
            "Raga Lalit Mangal"
            "Raga Lalit Pancham"
            "Raga Malani"
            "Raga Malayamarutam"
            "Raga Des Malhar"
            "Raga Hauns Manjiri"
            "Raga Kamal Manohari"
            "Raga Prabhavati"
            "Raga Ramkali"
            "Raga Dev Ranjani"
            "Raga Kamal Ranjani"
            "Raga Ras Chandra"
            "Raga Revati"
            "Raga Bhav Sakh"
            "Raga Lachchha Sakh"
            "Raga Saveri"
            "Raga Shobhavari"
            "Raga Shreevanti"
            "Raga Sorath"
            "Raga Sourashtra Tank"
            "Raga Asa Todi"
            "Raga Bahaduri Todi"
            "Raga Bairagi Todi"
            "Raga Chhaya Todi"
            "Raga Darbari Todi"
            "Raga Gauri Todi"
            "Raga Hussaini Todi"
            "Raga Jaiwanti Todi"
            "Raga Laxmi Todi"
            "Raga Triveni"
            "Raga Zilaf"]

  :fourth  ["Raga Abheri"
            "Raga Asavari"
            "Raga Jogi Asavari"
            "Raga Komal Rishabh Asavari"
            "Raga Sindhura Asavari"
            "Raga Barwa"
            "Raga Adi Bhairavi"
            "Raga Jaij Bilawal"
            "Raga Nat Bilawal"
            "Raga Sukhiya Bilawal"
            "Raga Uday Chandrika"
            "Raga Charukeshi"
            "Raga Desi"
            "Raga Komal Desi"
            "Raga Dev Gandhar"
            "Raga Gandhari"
            "Raga Gyankali"
            "Raga Jaiwanti"
            "Raga Jaunpuri"
            "Raga Khat"
            "Raga Khokhar"
            "Raga Kripavati"
            "Raga Malagunji"
            "Raga Rudra Manjiri"
            "Raga Amba Manohari"
            "Raga Naat Kuranjika"
            "Raga Rakta Hauns"
            "Raga Kaam Ranjani"
            "Raga Dev Sakh"
            "Raga Sameri"
            "Raga Madhmaad Sarang"
            "Raga Miyan Ki Sarang"
            "Raga Anjani Todi"
            "Raga Bhupali Todi"
            "Raga Bilaskhani Todi"
            "Raga Gujari Todi"
            "Raga Lachari Todi"
            "Raga Miyan Ki Todi"
            "Raga Saheli Todi"
            "Raga Salag Varari"]

  :fifth   ["Raga Bhim"
            "Raga Udan Chandrika"
            "Raga Haunskinkini"
            "Raga Madhuvanti"
            "Raga Pat Manjiri"
            "Raga Chitta Mohini"
            "Raga Patadeep"
            "Raga Patdipaki"
            "Raga Badhans Sarang"
            "Raga Gaud Sarang"
            "Raga Lankadahan Sarang"
            "Raga Samant Sarang"
            "Raga Shuddha Sarang"
            "Raga Vrindavani Sarang"]

  :sixth   ["Raga Bhimpalasi"
            "Raga Puriya Dhanashree"
            "Raga Puriya Kalyan"
            "Raga Kolhaas"
            "Raga Latika"
            "Raga Maru"
            "Raga Maru Bihag"
            "Raga Marwa"
            "Raga Multani"
            "Raga Pilu"
            "Raga Poorvi"
            "Raga Kumud Prabha"
            "Raga Puriya"
            "Raga Shree"]

  :seventh ["Raga Kedar Bahar"
            "Raga Amrit Varshini"
            "Raga Sindhu Bahar"
            "Raga Bhup"
            "Raga Champak"
            "Raga Chandrakant"
            "Raga Uday Ravi Chandrika"
            "Raga Dhanashree"
            "Raga Gauri"
            "Raga Lalita Gauri"
            "Raga Haunsdhwani"
            "Raga Haunsnad"
            "Raga Saanjh Ki Hindol"
            "Raga Jaijaiwanti"
            "Raga Jaijaiwanti (Des Ang)"
            "Raga Jait"
            "Raga Janasamohini"
            "Raga Kafi"
            "Raga Kala Bharan"
            "Raga Chandra Kalyan"
            "Raga Durga Kalyan"
            "Raga Hem Kalyan"
            "Raga Jait Kalyan"
            "Raga Kesari Kalyan"
            "Raga Khem Kalyan"
            "Raga Lakshmi Kalyan"
            "Raga Purba Kalyan"
            "Raga Shuddha Kalyan"
            "Raga Shyam Kalyan"
            "Raga Yaman Kalyan"
            "Raga Kamod"
            "Raga Sughrai Kanada"
            "Raga Suha Kanada"
            "Raga Suha Sughrai Kanada"
            "Raga Kapi"
            "Raga Basanti Kedar"
            "Raga Jaldhar Kedar"
            "Raga Maluha Kedar"
            "Raga Nat Kedar"
            "Raga Khamaj"
            "Raga Koumari"
            "Raga Lalitavari"
            "Raga Maand"
            "Raga Malarani"
            "Raga Malashree"
            "Raga Malavi"
            "Raga Maligaura"
            "Raga Malin"
            "Raga Manohar"
            "Raga Motaki"
            "Raga Pahadi"
            "Raga Pancham"
            "Raga Rajeshwari"
            "Raga Ratnadeep"
            "Raga Reva"
            "Raga Saajgiri"
            "Raga Poorvi Sarang"
            "Raga Saraswati"
            "Raga Shimendra Madhyam"
            "Raga Shreetank"
            "Raga Tanki"
            "Raga Tilak Kamod"
            "Raga Tilang"
            "Raga Vijay"
            "Raga Yaman"]

  :eighth  ["Raga Abhogi"
            "Raga Asa"
            "Raga Audav Bageshree"
            "Raga Bageshree Bahar"
            "Raga Kanada Bahar"
            "Raga Rageshree Bahar"
            "Raga Bhinna Shadja"
            "Raga Bihag"
            "Raga Nat Bihag"
            "Raga Pat Bihag"
            "Raga Sawani Bihag"
            "Raga Bihagda"
            "Raga Chakradhar"
            "Raga Chandrakauns"
            "Raga Chandranandan"
            "Raga Chandraprabha"
            "Raga Chhayanat"
            "Raga Deepak"
            "Raga Deshakhya"
            "Raga Multani Dhanashree"
            "Raga Durga"
            "Raga Hameer"
            "Raga Harikauns"
            "Raga Hemant"
            "Raga Jaikauns"
            "Raga Jhinjhoti"
            "Raga Kaamaai"
            "Raga Kaamkesh"
            "Raga Kalawati"
            "Raga Gorakh Kalyan"
            "Raga Raj Kalyan"
            "Raga Samant Kalyan"
            "Raga Kamboji"
            "Raga Gop Kamboji"
            "Raga Bageshree Kanada"
            "Raga Darbari Kanada"
            "Raga Gunji Kanada"
            "Raga Hussaini Kanada"
            "Raga Nayaki Kanada"
            "Raga Shahana Kanada"
            "Raga Udan Kanta"
            "Raga Kedar"
            "Raga Chandni Kedar"
            "Raga Shyam Kedar"
            "Raga Khambavati"
            "Raga Kohal"
            "Raga Kumudaki"
            "Raga Lankeshree"
            "Raga Madhukauns"
            "Raga Madhuranjani"
            "Raga Jayant Malhar"
            "Raga Nat Malhar"
            "Raga Ahi Mohini"
            "Raga Nand"
            "Raga Narayani"
            "Raga Shuddha Nat"
            "Raga Nilambari"
            "Raga Pushp"
            "Raga Rageshree"
            "Raga Gou Ranjani"
            "Raga Jan Ranjani"
            "Raga Kusum Ranjani"
            "Raga Raag Ranjani"
            "Raga Saraswat Ranjani"
            "Raga Ravikosh"
            "Raga Rupeshwari"
            "Raga Naag Saravali"
            "Raga Shankara"
            "Raga Shivranjani"
            "Raga Hauns Shree"
            "Raga Vachaspati"
            "Raga Kantal Varari"
            "Raga Karank Varari"
            "Raga Viranch Mukhi"]})
